defer class loading at instanciation time for unix socket , as unix socket support is optional and some jars may be missing at runtime, we do not want NoClassDefFoundErrors on windows, by example.